version: "3.9"

services:
  app:
    build: .
    container_name: rag-chat-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/rag_chat_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      API_KEY: supersecretkey123
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    image: mysql:8.0
    container_name: rag-chat-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rag_chat_db
    ports:
      - "3307:3306"  # changed to 3307 to avoid local MySQL port conflicts
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  adminer:
    image: adminer
    container_name: rag-chat-adminer
    restart: always
    ports:
      - "8081:8080"

volumes:
  mysql_data:
