spring:
  application:
    name: rag-chat-storage

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/rag_chat_db}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  flyway:
    enabled: false

# API key read from .env file
app:
  api-key: ${API_KEY:supersecretkey123}

# Logging Configuration
logging:
  file:
    name: logs/rag-chat.log
  level:
    root: INFO
    com.rag.chat: DEBUG

# Actuator Endpoints (for health/info)
management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
